// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CostEstimateDbContext))]
    [Migration("20260529095737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Item", b =>
                {
                    b.Property<string>("ProdGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Caliper")
                        .HasColumnType("int");

                    b.Property<int?>("Cbnum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GSM")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ItemDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(20,4)");

                    b.Property<int?>("PPR")
                        .HasColumnType("int");

                    b.Property<string>("PType")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PType");

                    b.Property<string>("UM")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(20,4)");

                    b.HasKey("ProdGroup");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("backend.Models.PaperBoardPricing", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("PType")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PType");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Currcode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("EffectiveDate")
                        .HasColumnType("decimal(20,8)");

                    b.Property<string>("Group")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Group");

                    b.Property<decimal?>("Price_Bale")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("Price_MT")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("Price_Pound")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("Price_Sheet")
                        .HasColumnType("decimal(20,8)");

                    b.HasKey("ItemCode", "Vendor", "PType");

                    b.ToTable("PaperBoardPricing");
                });

            modelBuilder.Entity("backend.Models.Ptype", b =>
                {
                    b.Property<string>("PType")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PType");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DescLabel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PtypeDesc")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PType");

                    b.ToTable("Ptype");
                });

            modelBuilder.Entity("backend.Models.Vendors", b =>
                {
                    b.Property<string>("Vendnum")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Currcode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Group")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Group");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Vendnum");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
