// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CostEstimateDbContext))]
    partial class CostEstimateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Caliper")
                        .HasColumnType("int");

                    b.Property<int?>("Cbnum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GSM")
                        .HasColumnType("int");

                    b.Property<string>("ItemDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(20,4)");

                    b.Property<int?>("PPR")
                        .HasColumnType("int");

                    b.Property<string>("PType")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PType");

                    b.Property<string>("ProdGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UM")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(20,4)");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemCode = "CCG0250R",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 250,
                            ItemDesc = "CC Greyblack 250 GSM",
                            PType = "CC",
                            ProdGroup = "PAPER",
                            UM = "RL"
                        },
                        new
                        {
                            ItemCode = "CCG0250S",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 250,
                            ItemDesc = "CC Greyblack 250 GSM",
                            PType = "CC",
                            ProdGroup = "PAPER",
                            UM = "SH"
                        },
                        new
                        {
                            ItemCode = "FC0210R",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 210,
                            ItemDesc = "Foldcote 210 GSM",
                            PType = "FC",
                            ProdGroup = "PAPER",
                            UM = "RL"
                        },
                        new
                        {
                            ItemCode = "CB0230R",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 230,
                            ItemDesc = "Carrier Board 230 GSM",
                            PType = "CB",
                            ProdGroup = "PAPER",
                            UM = "RL"
                        },
                        new
                        {
                            ItemCode = "C1S008500250028S",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 85,
                            ItemDesc = "C1S Paper 85 GSM",
                            Length = 38m,
                            PType = "C1S",
                            ProdGroup = "PAPER",
                            UM = "SH",
                            Width = 25m
                        },
                        new
                        {
                            ItemCode = "C2S0080R",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 80,
                            ItemDesc = "C2S Paper 80 GSM",
                            PType = "C2S",
                            ProdGroup = "PAPER",
                            UM = "RL"
                        },
                        new
                        {
                            ItemCode = "BP0065R",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            GSM = 65,
                            ItemDesc = "WOODFREE BP 65 GSM",
                            PType = "BP",
                            ProdGroup = "PAPER",
                            UM = "RL"
                        });
                });

            modelBuilder.Entity("backend.Models.PaperBoardPricing", b =>
                {
                    b.Property<string>("PType")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PType");

                    b.Property<string>("Vendor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Currcode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("EffectiveDate")
                        .HasColumnType("decimal(20,8)");

                    b.Property<string>("Group")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Group");

                    b.Property<decimal?>("Price_Bale")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("Price_MT")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("Price_Pound")
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("Price_Sheet")
                        .HasColumnType("decimal(20,8)");

                    b.HasKey("PType", "Vendor", "ItemCode");

                    b.ToTable("PaperBoardPricing");

                    b.HasData(
                        new
                        {
                            PType = "CC",
                            Vendor = "IGHAPCL",
                            ItemCode = "CC250GS",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            EffectiveDate = 20250101.00m,
                            Group = "IMPORTED",
                            Price_MT = 540m
                        },
                        new
                        {
                            PType = "CC",
                            Vendor = "IGHAPCL",
                            ItemCode = "CC300GS",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            EffectiveDate = 20250101.00m,
                            Group = "IMPORTED",
                            Price_MT = 515m
                        },
                        new
                        {
                            PType = "CC",
                            Vendor = "IGHAPCL",
                            ItemCode = "CC350GS",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            EffectiveDate = 20250101.00m,
                            Group = "IMPORTED",
                            Price_MT = 500m
                        },
                        new
                        {
                            PType = "FC",
                            Vendor = "UNASGND",
                            ItemCode = "FC210GR",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            EffectiveDate = 20250101.00m,
                            Group = "IMPORTED",
                            Price_MT = 650m
                        },
                        new
                        {
                            PType = "CB",
                            Vendor = "IGSEPCL",
                            ItemCode = "CB230G",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            EffectiveDate = 20250101.00m,
                            Group = "IMPORTED",
                            Price_MT = 630m
                        },
                        new
                        {
                            PType = "C1S",
                            Vendor = "IGOFSNL",
                            ItemCode = "C1S085G",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            EffectiveDate = 20250101.00m,
                            Group = "IMPORTED",
                            Price_MT = 780m
                        });
                });

            modelBuilder.Entity("backend.Models.Ptype", b =>
                {
                    b.Property<string>("PType")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PType");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DescLabel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PtypeDesc")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PType");

                    b.ToTable("Ptype");

                    b.HasData(
                        new
                        {
                            PType = "BP",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            DescLabel = "Book Paper",
                            PtypeDesc = "Book Paper"
                        },
                        new
                        {
                            PType = "CB",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            DescLabel = "CB",
                            PtypeDesc = "Carrier Board"
                        },
                        new
                        {
                            PType = "CC",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            DescLabel = "CC Greyblack",
                            PtypeDesc = "CC Greyblack"
                        },
                        new
                        {
                            PType = "C1S",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            DescLabel = "C1S",
                            PtypeDesc = "C1S"
                        },
                        new
                        {
                            PType = "C2S",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            DescLabel = "C2S",
                            PtypeDesc = "C2S"
                        },
                        new
                        {
                            PType = "FC",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            DescLabel = "Foldcote",
                            PtypeDesc = "Foldcote"
                        });
                });

            modelBuilder.Entity("backend.Models.Vendors", b =>
                {
                    b.Property<string>("Vendnum")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Currcode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Group")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Group");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Vendnum");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Vendnum = "IGHAPCL",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            Group = "IMPORTED",
                            Name = "HANSOL PAPER CO. LTD."
                        },
                        new
                        {
                            Vendnum = "IGSEPCL",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            Group = "IMPORTED",
                            Name = "STORA ENSO (GUANGXI) PACKAGING"
                        },
                        new
                        {
                            Vendnum = "IGOFSNL",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            Group = "IMPORTED",
                            Name = "OJI FIBRE SOLUTIONS (NZ) LIMITED"
                        },
                        new
                        {
                            Vendnum = "IGSPHK2",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "USD",
                            Group = "IMPORTED",
                            Name = "SAPPI PAPIER HOLDING GmBh"
                        },
                        new
                        {
                            Vendnum = "UNASGND",
                            CreateDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "SystemSeed",
                            Currcode = "PHP",
                            Group = "NONE",
                            Name = "Pending Vendor Assignment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
